version: "3.9"

services:
  mysql:
    image: mysql:8.0.28
    container_name: mysql-nest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nest
    volumes:
      - .docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf